// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYWxgj3m-FmVZRzdIdBDexx0IYixMO7J0',
    appId: '1:426531506044:web:c769ff098f97cfe1d2c6f9',
    messagingSenderId: '426531506044',
    projectId: 'h-messaging',
    authDomain: 'h-messaging.firebaseapp.com',
    storageBucket: 'h-messaging.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWarVU1lNEy2j1jFpE4LQzLZ-PCig8W14',
    appId: '1:426531506044:android:0932fbc2f8bc52dcd2c6f9',
    messagingSenderId: '426531506044',
    projectId: 'h-messaging',
    storageBucket: 'h-messaging.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBl2O1PAS1KxS6YNihA2UP_bdRmR9rMyN8',
    appId: '1:426531506044:ios:c6deef2134025a57d2c6f9',
    messagingSenderId: '426531506044',
    projectId: 'h-messaging',
    storageBucket: 'h-messaging.appspot.com',
    iosClientId: '426531506044-gu5l0ee2j2gds595pp67f6rc4c6rjtsm.apps.googleusercontent.com',
    iosBundleId: 'com.example.assignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBl2O1PAS1KxS6YNihA2UP_bdRmR9rMyN8',
    appId: '1:426531506044:ios:c6deef2134025a57d2c6f9',
    messagingSenderId: '426531506044',
    projectId: 'h-messaging',
    storageBucket: 'h-messaging.appspot.com',
    iosClientId: '426531506044-gu5l0ee2j2gds595pp67f6rc4c6rjtsm.apps.googleusercontent.com',
    iosBundleId: 'com.example.assignment',
  );
}
